/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vista.Bancos;
import Controlador.Bancos.clsCarreras;
import Modelo.Bancos.CarrerasDAO;
import java.io.File;
import javax.swing.table.DefaultTableModel;

public class frmCarreras extends javax.swing.JFrame {

    private final CarrerasDAO carrerasDAO = new CarrerasDAO();

    public frmCarreras() {
        initComponents();
        setTitle("Mantenimiento de Carreras");
        cargarTabla();
        configurarSeleccionTabla();
    }

    // ── Carga la tabla ───────────────────────────────────────────
    private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"ID", "Nombre de la Carrera", "Código de la Facultad", "Estatus de la Carrera"}, 0
        ) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };

        for (clsCarreras c : carrerasDAO.listar()) {
            modelo.addRow(new Object[]{
                c.getCodigo_carrera(),
                c.getNombre_carrera(),
                c.getCodigo_facultad(),
                c.getEstatus_carrera()
            });
        }
        Tabla.setModel(modelo);
    }

    // ── Clic en fila → llena campos ──────────────────────────────
    private void configurarSeleccionTabla() {
        Tabla.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && Tabla.getSelectedRow() != -1) {
                int fila = Tabla.getSelectedRow();
                txtbuscado.setText(Tabla.getValueAt(fila, 0).toString());
                jTextField1.setText(Tabla.getValueAt(fila, 1).toString());
                jTextField2.setText(Tabla.getValueAt(fila, 2).toString());
                jTextField3.setText(Tabla.getValueAt(fila, 3).toString());
            }
        });
    }

    // ── Valida campos obligatorios ───────────────────────────────
    private boolean camposCompletos() {
        if (txtbuscado.getText().trim().isEmpty() ||
            jTextField1.getText().trim().isEmpty() ||
            jTextField2.getText().trim().isEmpty() ||
            jTextField3.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Complete todos los campos: Código, Nombre, Código Facultad y Estatus.",
                "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    // ── Construye objeto desde formulario ────────────────────────
    private clsCarreras getObjetoDeFormulario() {
        clsCarreras c = new clsCarreras();
        c.setCodigo_carrera(txtbuscado.getText().trim());
        c.setNombre_carrera(jTextField1.getText().trim());
        c.setCodigo_facultad(jTextField2.getText().trim());
        c.setEstatus_carrera(jTextField3.getText().trim());
        return c;
    }

    // ── Limpia todos los campos ──────────────────────────────────
    private void limpiarCampos() {
        txtbuscado.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        Tabla.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ayuda = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        txtbuscado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        actualizaar = new javax.swing.JButton();
        buscar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        reporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ayuda.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        ayuda.setText("Ayudas");
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Código de la facultad");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Estatus Facultad");

        Limpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        actualizaar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        actualizaar.setText("Actualizar");
        actualizaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaarActionPerformed(evt);
            }
        });

        buscar2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        buscar2.setText("Buscar");
        buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar2ActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre Carrea", "Código de la Facultad", "Estatus Facultad"
            }
        ));
        jScrollPane2.setViewportView(Tabla);

        reporte.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        reporte.setText("Reportes");
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Nombre Carrea");

        jLabel5.setFont(new java.awt.Font("Swis721 Blk BT", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Carreas");
        jLabel5.setToolTipText("");

        label4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label4.setText("ID:");

        agregar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(actualizaar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5)))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Limpiar))
                .addGap(84, 84, 84)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(agregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(buscar2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label4)
                            .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(actualizaar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(reporte)
                        .addGap(33, 33, 33)
                        .addComponent(ayuda)
                        .addGap(29, 29, 29)
                        .addComponent(Limpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        try {
            String ruta = "src\\main\\java\\Ayudas\\Bancos\\Ayuda Bancos.chm";
            File archivo = new File(ruta);
            if (archivo.exists()) {
                Runtime.getRuntime().exec("hh.exe \"" + ruta + "\"");
            } else {
                System.out.println("La ayuda no fue encontrada");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    
    }//GEN-LAST:event_ayudaActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
         if (txtbuscado.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Seleccione una carrera para eliminar.", "Atención",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar esta carrera?",
            "Confirmar eliminación", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;
        try {
            String codigo = txtbuscado.getText().trim();
            carrerasDAO.delete(codigo);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Carrera eliminada correctamente.", "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            frmBitacoraBancaria.registrarBitacora(
                "DELETE", "Carreras", null,
                "Código: " + txtbuscado.getText().trim() +
                " | Nombre: " + jTextField1.getText().trim(),
                null, "Carrera eliminada");
            cargarTabla();
            limpiarCampos();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al eliminar: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Está seguro de ELIMINAR TODOS los registros?\nEsta acción no se puede deshacer.",
            "Confirmar limpieza total",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;
        try {
            carrerasDAO.deleteAll();
            frmBitacoraBancaria.registrarBitacora(
                "DELETE ALL", "Carreras", null, null, null,
                "Se eliminaron todos los registros de la tabla Carreras");
            javax.swing.JOptionPane.showMessageDialog(this,
                "Todos los registros fueron eliminados.", "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            cargarTabla();
            limpiarCampos();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al limpiar: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LimpiarActionPerformed

    private void actualizaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaarActionPerformed
         if (txtbuscado.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Seleccione una carrera para actualizar.", "Atención",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!camposCompletos()) return;
        try {
            clsCarreras c = getObjetoDeFormulario();
            carrerasDAO.update(c);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Carrera actualizada correctamente.", "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            frmBitacoraBancaria.registrarBitacora(
                "UPDATE", "Carreras", null, null,
                "Código: " + txtbuscado.getText().trim() +
                " | Nombre: " + jTextField1.getText().trim() +
                " | Facultad: " + jTextField2.getText().trim() +
                " | Estatus: " + jTextField3.getText().trim(),
                "Carrera actualizada");
            cargarTabla();
            limpiarCampos();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al actualizar: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_actualizaarActionPerformed

    private void buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar2ActionPerformed
      if (txtbuscado.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Ingrese un código para buscar.", "Atención",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            clsCarreras c = carrerasDAO.query(txtbuscado.getText().trim());
            if (c != null) {
                jTextField1.setText(c.getNombre_carrera());
                jTextField2.setText(c.getCodigo_facultad());
                jTextField3.setText(c.getEstatus_carrera());
                frmBitacoraBancaria.registrarBitacora(
                    "SELECT", "Carreras", null, null, null,
                    "Consulta de carrera por código: " + txtbuscado.getText().trim());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encontró carrera con código: " + txtbuscado.getText().trim(),
                    "Sin resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al buscar: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buscar2ActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
       java.sql.Connection conn = null;
    try {
        conn = Modelo.Conexion.getConnection();
        
        
        String ruta = new java.io.File("").getAbsolutePath() 
                    + "\\src\\main\\java\\Reportes\\Bancos\\RCarreas.jrxml";
        
        System.out.println("Buscando reporte en: " + ruta); // Para verificar en consola
        
        java.io.File archivo = new java.io.File(ruta);
        if (!archivo.exists()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontró el archivo del reporte en:\n" + ruta,
                "Archivo no encontrado", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        java.util.Map<String, Object> parametros = new java.util.HashMap<>();
        
        net.sf.jasperreports.engine.JasperReport reporte =
            net.sf.jasperreports.engine.JasperCompileManager.compileReport(ruta);
        
        net.sf.jasperreports.engine.JasperPrint print =
          net.sf.jasperreports.engine.JasperFillManager.fillReport(reporte, parametros, conn);
        
        net.sf.jasperreports.engine.JasperExportManager.exportReportToPdfFile(print,"reporte.pdf");
        net.sf.jasperreports.swing.JRViewer viewer = new net.sf.jasperreports.swing.JRViewer(print);
        
        javax.swing.JFrame frame = new javax.swing.JFrame("Reporte de Clientes");
        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        frame.add(viewer);
        frame.setVisible(true);
        
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al generar el reporte:\n" + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } finally {
        if (conn != null) {
            try { conn.close(); } catch (Exception ex) { ex.printStackTrace(); }
        }
    }
    }//GEN-LAST:event_reporteActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if (!camposCompletos()) return;
        try {
            clsCarreras c = getObjetoDeFormulario();
            carrerasDAO.insert(c);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Carrera registrada correctamente.", "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            frmBitacoraBancaria.registrarBitacora(
                "INSERT", "Carreras", null, null,
                "Código: " + txtbuscado.getText().trim() +
                " | Nombre: " + jTextField1.getText().trim() +
                " | Facultad: " + jTextField2.getText().trim() +
                " | Estatus: " + jTextField3.getText().trim(),
                "Carrera registrada");
            cargarTabla();
            limpiarCampos();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al agregar: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarreras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton actualizaar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton ayuda;
    private javax.swing.JButton buscar2;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel label4;
    private javax.swing.JButton reporte;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
